version: '3'

services:
  app:
    build: .
    user: ${UID}
    volumes:
      - ./datasets:/datasets:ro
      - ./reports:/reports:rw
      - ./ci-repo:/repo:rw
      - ./ci-tex-cache:/home/ci/.cache/Tectonic:rw
      - ./ci-cargo-cache:/home/ci/.cargo:rw
